############################################################################
#                                     GAP package
#
#  Copyright 2020,                    Kamal Saleh
#                                     Siegen University
#
#! @Chapter HomotopyCategories
#
#############################################################################

InfoHomotopyCategories := NewInfoClass( "InfoHomotopyCategories" );

SetInfoLevel( InfoHomotopyCategories, 1 );

DeclareCategory( "IsHomotopyCategory",
                 IsStableCategory );

KeyDependentOperation( "HomotopyCategory", IsCapCategory, IsBool, ReturnTrue );

DeclareAttribute( "HomotopyCategoryAttr", IsCapCategory );

DeclareAttribute( "DefiningCategory", IsHomotopyCategory );

# @Description
# The input is a chain or cochain complex category $B=C(A)$ and an integer $n$. 
# The outout is the additive full subcategory generated by complexes concentrated in degree $n$.
# @Arguments B, n
# @Returns a CAP category
KeyDependentOperation( "FullSubcategoryGeneratedByObjectsConcentratedInDegree",
    IsHomotopyCategory, IsInt, ReturnTrue
);

DeclareAttribute( "TotalComplexUsingMappingCone", IsChainComplex );

DeclareGlobalFunction( "ADD_HOM_STRUCTURE_ON_OBJECTS_IN_HOMOTOPY_CATEGORY_OVER_CHAINS" );

DeclareGlobalFunction( "ADD_HOM_STRUCTURE_ON_MORPHISMS_IN_HOMOTOPY_CATEGORY_OVER_CHAINS" );

DeclareGlobalFunction( "ADD_INTERPRET_MORPHISM_AS_MORPHISM_FROM_DISTINGUISHED_OBJECT_TO_HOMOMORPHISM_STRUCTURE_IN_HOMOTOPY_CATEGORY_OVER_CHAINS" );

DeclareGlobalFunction( "ADD_INTERPRET_MORPHISM_FROM_DISTINGUISHED_OBJECT_TO_HOMOMORPHISM_STRUCTURE_AS_MORPHISM_IN_HOMOTOPY_CATEGORY_OVER_CHAINS" );

DeclareGlobalFunction( "ADD_DISTINGUISHED_OBJECT_OF_HOMOMORPHISM_STRUCTURE_IN_HOMOTOPY_CATEGORY_OVER_CHAINS" );

DeclareGlobalFunction( "ADD_HOM_STRUCTURE_TO_HOMOTOPY_CATEGORY_OVER_CHAINS" );

DeclareGlobalFunction( "ADD_HOM_STRUCTURE_TO_HOMOTOPY_CATEGORY_OVER_COCHAINS" );

DeclareGlobalFunction( "IS_COLIFTABLE_THROUGH_COLIFTING_OBJECT_IN_HOMOTOPY_CATEGORY" );

