# SPDX-License-Identifier: GPL-2.0-or-later
# DerivedCategories: Derived categories of Abelian categories
#
# Declarations
#
##
##  Functors
##
#############################################################################

DeclareAttribute( "HomFunctorToCategoryOfFunctors",
        IsStrongExceptionalCollection );

#! @Description
#!  The argument is an exceptional collection <A>E</A> which is defined by some full
#!  subcategory generated by finite number of objects $(E_i)_i$ in some category $C$
#!  with homomorphism structure. The output is the functor
#!  $\mathrm{Hom}(\oplus_i E_i,-):C \to \mathrm{mod}\mbox{-}\mathrm{End}(\oplus_i E_i)$.
#! @Arguments collection
#! @Returns a functor
DeclareAttribute( "HomFunctorToCategoryOfQuiverRepresentations",
        IsStrongExceptionalCollection );

#! @Description
#!  The argument is an exceptional collection <A>E</A> which is defined by some full
#!  subcategory generated by finite number of objects $(E_i)_i$ in a category of quiver
#!  representations $C$. The output is the functor $\mathrm{Hom}(\oplus_i E_i,-)$:
#!  <C>FullSubcategoryGeneratedByIndecomposableInjectiveObjects</C>$(C)
#!  \to \mathrm{mod}\mbox{-}\mathrm{End}(\oplus_i E_i)$.
#! @Arguments collection
#! @Returns a functor
DeclareAttribute( "HomFunctorToCategoryOfQuiverRepresentationsOnIndecomposableInjectiveObjects",
        IsStrongExceptionalCollection );

#! @Description
#!  The argument is an exceptional collection <A>E</A> which is defined by some
#!  full subcategory generated by finite number of objects
#!  $(E_i)_i$ in a category of quiver representations $C$. The output is the functor
#!  $\mathrm{Hom}(\oplus_i E_i,-)$:<C>FullSubcategoryGeneratedByInjectiveObjects</C>$(C)
#!  \to \mathrm{mod}\mbox{-}\mathrm{End}(\oplus_i E_i)$.
#! @Arguments collection
#! @Returns a functor
DeclareAttribute( "HomFunctorToCategoryOfQuiverRepresentationsOnInjectiveObjects",
        IsStrongExceptionalCollection );


DeclareAttribute( "HomFunctorToCategoryOfQuiverRepresentationsOnIndecomposableProjectiveObjects",
        IsStrongExceptionalCollection );

DeclareAttribute( "HomFunctorToCategoryOfQuiverRepresentationsOnProjectiveObjects",
        IsStrongExceptionalCollection );

DeclareAttribute( "HomFunctorToCategoryOfQuiverRepresentationsOnDefiningCategory",
        IsStrongExceptionalCollection );

DeclareAttribute( "HomFunctorToCategoryOfQuiverRepresentationsOnBaseCategory",
        IsStrongExceptionalCollection );

