#############################################################################
##
## DerivedCategories: Derived categories for abelian categories
##
## Copyright 2020, Kamal Saleh, University of Siegen
##
##  Functors
##
#############################################################################

#! @Description
#!  The argument is an exceptional collection <A>E</A> which is defined by some full
#!  subcategory generated by finite number of objects $(E_i)_i$ in some category $C$
#!  with homomorphism structure. The output is the functor
#!  $\mathrm{Hom}(\oplus_i E_i,-):C \to \mathrm{mod}\mbox{-}\mathrm{End}(\oplus_i E_i)$.
#! @Arguments collection
#! @Returns a functor
DeclareAttribute( "HomFunctorByExceptionalCollection",
        IsExceptionalCollection );

#! @Description
#!  The argument is an exceptional collection <A>E</A> which is defined by some full
#!  subcategory generated by finite number of objects $(E_i)_i$ in a category of quiver
#!  representations $C$. The output is the functor $\mathrm{Hom}(\oplus_i E_i,-)$:
#!  <C>FullSubcategoryGeneratedByIndecInjectiveObjects</C>$(C)
#!  \to \mathrm{mod}\mbox{-}\mathrm{End}(\oplus_i E_i)$.
#! @Arguments collection
#! @Returns a functor
DeclareAttribute( "RestrictionOfHomFunctorByExceptionalCollectionToIndecInjectiveObjects",
        IsExceptionalCollection );

#! @Description
#!  The argument is an exceptional collection <A>E</A> which is defined by some
#!  full subcategory generated by finite number of objects
#!  $(E_i)_i$ in a category of quiver representations $C$. The output is the functor
#!  $\mathrm{Hom}(\oplus_i E_i,-)$:<C>FullSubcategoryGeneratedByInjectiveObjects</C>$(C)
#!  \to \mathrm{mod}\mbox{-}\mathrm{End}(\oplus_i E_i)$.
#! @Arguments collection
#! @Returns a functor
DeclareAttribute( "RestrictionOfHomFunctorByExceptionalCollectionToInjectiveObjects",
        IsExceptionalCollection );


DeclareAttribute( "RestrictionOfHomFunctorByExceptionalCollectionToIndecProjectiveObjects",
        IsExceptionalCollection );

DeclareAttribute( "RestrictionOfHomFunctorByExceptionalCollectionToProjectiveObjects",
        IsExceptionalCollection );

DeclareAttribute( "RestrictionOfHomFunctorByExceptionalCollectionToAdditiveClosure",
        IsExceptionalCollection );


